author = "EeeLee"
name = "Eeriea S3"
pack-format = "packwiz:1.1.0"
version = "3.0.0"

[index]
file = "index.toml"
hash = "62fb0567057519a2d3ab414afeee9942c0c72e96383db9cc3e73bb7ea6eae0ed"
hash-format = "sha256"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
