author = "EeeLee"
name = "Eeriea S3"
pack-format = "packwiz:1.1.0"
version = "3.0.0"

[index]
file = "index.toml"
hash = "64c7fc25a03b14f6a69d0d2c737e15103587320eb6f6ec803d0c54f229062d86"
hash-format = "sha256"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
