author = "EeeLee"
name = "Eeriea S3"
pack-format = "packwiz:1.1.0"
version = "3.0.0"

[index]
file = "index.toml"
hash = "f21e938fac289aab1a2466edd13eb58490313498e02f67ea9d33b386c1e5eec5"
hash-format = "sha256"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
